allowedCopyrightHolders:
  - "Google LLC"
allowedLicenses:
  - "Apache-2.0"
sourceFileExtensions:
  - "yaml"
  - "yml"
  - "sh"
  - "proto"
  - "Dockerfile"
  - "py"
  - "text"
ignoreFiles:
  - ".github/release-please.yml"
  - ".github/release-trigger.yml"
  - ".github/header-checker-lint.yml"
  - ".github/sync-repo-settings.yaml"
  - ".kokoro/**"
  - "**/requirements.txt"
  - "**/requirements*.txt"
