# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - id: create Dockerfile
    name: ubuntu
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        echo "FROM python:${_VERSION}
        COPY . .
        RUN pip install -r requirements.txt
        RUN pip install .[test]" > Dockerfile-base
        cat Dockerfile-base

  - id: "docker-build"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_IMAGE_NAME}", "-f", "Dockerfile-base", "."]

  - id: "docker-push"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE_NAME}"]

  - id: "docker-layer"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        echo "FROM $_IMAGE_NAME
        COPY --from=gcr.io/cloud-sql-connectors/cloud-sql-proxy /cloud-sql-proxy /cloudsql/cloud-sql-proxy" > Dockerfile-proxy;

        docker build -f Dockerfile-proxy -t ${_IMAGE_NAME}-proxy .

  - id: Run integration tests
    name: "${_IMAGE_NAME}-proxy"
    entrypoint: /bin/bash
    env:
      - "PROJECT_ID=$PROJECT_ID"
      - "INSTANCE_ID=$_INSTANCE_ID"
      - "DATABASE_ID=$_DATABASE_ID"
      - "REGION=$_REGION"
      - "IP_ADDRESS=$_IP_ADDRESS"
    secretEnv: ["DB_USER", "DB_PASSWORD", "IAM_ACCOUNT"]
    args:
      - "-c"
      - |
        /cloudsql/cloud-sql-proxy --port ${_DATABASE_PORT} ${_INSTANCE_CONNECTION_NAME} & sleep 2;
        pytest --cov=langchain_google_cloud_sql_pg --cov-config=.coveragerc tests/

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/langchain-test-pg-username/versions/1
      env: "DB_USER"
    - versionName: projects/$PROJECT_ID/secrets/langchain-test-pg-password/versions/1
      env: "DB_PASSWORD"
    - versionName: projects/$PROJECT_ID/secrets/service_account_email/versions/1
      env: "IAM_ACCOUNT"

substitutions:
  _IMAGE_NAME: us-central1-docker.pkg.dev/${PROJECT_ID}/containers/test-proxy
  _INSTANCE_CONNECTION_NAME: ${PROJECT_ID}:${_REGION}:${_INSTANCE_ID}
  _DATABASE_PORT: "5432"
  _DATABASE_ID: test-database
  _REGION: us-central1
  _VERSION: "3.8"
  _IP_ADDRESS: "127.0.0.1"

options:
  dynamicSubstitutions: true
