# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - id: Install dependencies
    name: python:${_VERSION}
    entrypoint: pip
    args: ["install", "--user", "-r", "requirements.txt"]

  - id: Install module (and test requirements)
    name: python:${_VERSION}
    entrypoint: pip
    args: ["install", ".[test]", "--user"]

  - id: proxy-install
    name: alpine:3.10
    entrypoint: sh
    args:
      - -c
      - |
        wget -O /workspace/cloud_sql_proxy https://storage.googleapis.com/cloudsql-proxy/v1.37.0/cloud_sql_proxy.linux.386
        chmod +x /workspace/cloud_sql_proxy

  - id: Run integration tests
    name: python:${_VERSION}
    entrypoint: /bin/bash
    env:
      - "PROJECT_ID=$PROJECT_ID"
      - "INSTANCE_ID=$_INSTANCE_ID"
      - "DATABASE_ID=$_DATABASE_ID"
      - "REGION=$_REGION"
      - "IP_ADDRESS=$_IP_ADDRESS"
    secretEnv: ["DB_USER", "DB_PASSWORD", "IAM_ACCOUNT"]
    args:
      - "-c"
      - |
        /workspace/cloud_sql_proxy -dir=/workspace -instances=${_INSTANCE_CONNECTION_NAME}=tcp:$_IP_ADDRESS:$_DATABASE_PORT  & sleep 2;
        python -m pytest --cov=langchain_google_cloud_sql_pg --cov-config=.coveragerc tests/

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/langchain-test-pg-username/versions/1
      env: "DB_USER"
    - versionName: projects/$PROJECT_ID/secrets/langchain-test-pg-password/versions/1
      env: "DB_PASSWORD"
    - versionName: projects/$PROJECT_ID/secrets/service_account_email/versions/1
      env: "IAM_ACCOUNT"

substitutions:
  _INSTANCE_CONNECTION_NAME: ${PROJECT_ID}:${_REGION}:${_INSTANCE_ID}
  _DATABASE_PORT: "5432"
  _DATABASE_ID: test-database
  _REGION: us-central1
  _VERSION: "3.8"
  _IP_ADDRESS: "127.0.0.1"

options:
  dynamicSubstitutions: true
